version: "2"

services:
  
  bitrix-env:
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - SYS_ADMIN
    tmpfs:
      - /run
    tty: true
    stdin_open: true
    mem_limit: '1g'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#      - /var/www:/home/bitrix/www
